### ISSUE TITLE
--paper-badge-width and --paper-badge-height does not work

### ISSUE THREAD

**Issue by arnabk** [PolymerElements/paper-badge#17]
I tried to change this value, but it has not effect. Is there any working example proving that these parameters work?

**Comment by notwaldorf** [comment]
Yup, here's a jsbin that demos that: https://jsbin.com/huqupo/2/edit?html,output

I think the key is to make sure that your style is applied inside of a `custom-style` block, like so:
```css
<style is="custom-style">
  paper-badge {
    --paper-badge-width: 40px;
    --paper-badge-height: 40px; 
  }
</style>
```
